//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Models.QuestionAndAnswer.Persistence.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextualAnswer
    {
        public TextualAnswer()
        {
            this.TextualQuestions = new HashSet<TextualQuestion>();
        }
    
        public int ID { get; set; }
        public string Text { get; set; }
    
        public virtual ICollection<TextualQuestion> TextualQuestions { get; set; }
    }
}
