//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Messages", Namespace="http://schemas.datacontract.org/2004/07/JJ.Presentation.QuestionAndAnswer.AppService")]
    [System.SerializableAttribute()]
    public partial class Messages : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreYouSureYouWishToDeleteTheFollowingQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExplanationOfIsManualWithParenthesisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoCategoriesAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoQuestionsFoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionIsDeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreYouSureYouWishToDeleteTheFollowingQuestion {
            get {
                return this.AreYouSureYouWishToDeleteTheFollowingQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.AreYouSureYouWishToDeleteTheFollowingQuestionField, value) != true)) {
                    this.AreYouSureYouWishToDeleteTheFollowingQuestionField = value;
                    this.RaisePropertyChanged("AreYouSureYouWishToDeleteTheFollowingQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExplanationOfIsManualWithParenthesis {
            get {
                return this.ExplanationOfIsManualWithParenthesisField;
            }
            set {
                if ((object.ReferenceEquals(this.ExplanationOfIsManualWithParenthesisField, value) != true)) {
                    this.ExplanationOfIsManualWithParenthesisField = value;
                    this.RaisePropertyChanged("ExplanationOfIsManualWithParenthesis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoCategoriesAvailable {
            get {
                return this.NoCategoriesAvailableField;
            }
            set {
                if ((object.ReferenceEquals(this.NoCategoriesAvailableField, value) != true)) {
                    this.NoCategoriesAvailableField = value;
                    this.RaisePropertyChanged("NoCategoriesAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoQuestionsFound {
            get {
                return this.NoQuestionsFoundField;
            }
            set {
                if ((object.ReferenceEquals(this.NoQuestionsFoundField, value) != true)) {
                    this.NoQuestionsFoundField = value;
                    this.RaisePropertyChanged("NoQuestionsFound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionIsDeleted {
            get {
                return this.QuestionIsDeletedField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionIsDeletedField, value) != true)) {
                    this.QuestionIsDeletedField = value;
                    this.RaisePropertyChanged("QuestionIsDeleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Titles", Namespace="http://schemas.datacontract.org/2004/07/JJ.Presentation.QuestionAndAnswer.AppService")]
    [System.SerializableAttribute()]
    public partial class Titles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvailableCategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BackToListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentFlaggedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentFlagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentIsFlaggedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentManagementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentSourcesAndImportsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeleteQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlagContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlaggedContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HasActiveFlagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HideAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NextQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoQuestionsFoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelectCategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShowAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTrainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatisticsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TheCorrectAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnflagContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInformation {
            get {
                return this.AdditionalInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInformationField, value) != true)) {
                    this.AdditionalInformationField = value;
                    this.RaisePropertyChanged("AdditionalInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvailableCategories {
            get {
                return this.AvailableCategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableCategoriesField, value) != true)) {
                    this.AvailableCategoriesField = value;
                    this.RaisePropertyChanged("AvailableCategories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BackToList {
            get {
                return this.BackToListField;
            }
            set {
                if ((object.ReferenceEquals(this.BackToListField, value) != true)) {
                    this.BackToListField = value;
                    this.RaisePropertyChanged("BackToList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Confirm {
            get {
                return this.ConfirmField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmField, value) != true)) {
                    this.ConfirmField = value;
                    this.RaisePropertyChanged("Confirm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentFlaggedBy {
            get {
                return this.ContentFlaggedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentFlaggedByField, value) != true)) {
                    this.ContentFlaggedByField = value;
                    this.RaisePropertyChanged("ContentFlaggedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentFlags {
            get {
                return this.ContentFlagsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentFlagsField, value) != true)) {
                    this.ContentFlagsField = value;
                    this.RaisePropertyChanged("ContentFlags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentIsFlagged {
            get {
                return this.ContentIsFlaggedField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentIsFlaggedField, value) != true)) {
                    this.ContentIsFlaggedField = value;
                    this.RaisePropertyChanged("ContentIsFlagged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentManagement {
            get {
                return this.ContentManagementField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentManagementField, value) != true)) {
                    this.ContentManagementField = value;
                    this.RaisePropertyChanged("ContentManagement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentSourcesAndImports {
            get {
                return this.ContentSourcesAndImportsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentSourcesAndImportsField, value) != true)) {
                    this.ContentSourcesAndImportsField = value;
                    this.RaisePropertyChanged("ContentSourcesAndImports");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateQuestion {
            get {
                return this.CreateQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateQuestionField, value) != true)) {
                    this.CreateQuestionField = value;
                    this.RaisePropertyChanged("CreateQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeleteQuestion {
            get {
                return this.DeleteQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.DeleteQuestionField, value) != true)) {
                    this.DeleteQuestionField = value;
                    this.RaisePropertyChanged("DeleteQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EditQuestion {
            get {
                return this.EditQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.EditQuestionField, value) != true)) {
                    this.EditQuestionField = value;
                    this.RaisePropertyChanged("EditQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlagContent {
            get {
                return this.FlagContentField;
            }
            set {
                if ((object.ReferenceEquals(this.FlagContentField, value) != true)) {
                    this.FlagContentField = value;
                    this.RaisePropertyChanged("FlagContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlaggedContent {
            get {
                return this.FlaggedContentField;
            }
            set {
                if ((object.ReferenceEquals(this.FlaggedContentField, value) != true)) {
                    this.FlaggedContentField = value;
                    this.RaisePropertyChanged("FlaggedContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string General {
            get {
                return this.GeneralField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralField, value) != true)) {
                    this.GeneralField = value;
                    this.RaisePropertyChanged("General");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HasActiveFlags {
            get {
                return this.HasActiveFlagsField;
            }
            set {
                if ((object.ReferenceEquals(this.HasActiveFlagsField, value) != true)) {
                    this.HasActiveFlagsField = value;
                    this.RaisePropertyChanged("HasActiveFlags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HideAnswer {
            get {
                return this.HideAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.HideAnswerField, value) != true)) {
                    this.HideAnswerField = value;
                    this.RaisePropertyChanged("HideAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Links {
            get {
                return this.LinksField;
            }
            set {
                if ((object.ReferenceEquals(this.LinksField, value) != true)) {
                    this.LinksField = value;
                    this.RaisePropertyChanged("Links");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextQuestion {
            get {
                return this.NextQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.NextQuestionField, value) != true)) {
                    this.NextQuestionField = value;
                    this.RaisePropertyChanged("NextQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoQuestionsFound {
            get {
                return this.NoQuestionsFoundField;
            }
            set {
                if ((object.ReferenceEquals(this.NoQuestionsFoundField, value) != true)) {
                    this.NoQuestionsFoundField = value;
                    this.RaisePropertyChanged("NoQuestionsFound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionDetails {
            get {
                return this.QuestionDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionDetailsField, value) != true)) {
                    this.QuestionDetailsField = value;
                    this.RaisePropertyChanged("QuestionDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectCategories {
            get {
                return this.SelectCategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectCategoriesField, value) != true)) {
                    this.SelectCategoriesField = value;
                    this.RaisePropertyChanged("SelectCategories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Selection {
            get {
                return this.SelectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectionField, value) != true)) {
                    this.SelectionField = value;
                    this.RaisePropertyChanged("Selection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShowAnswer {
            get {
                return this.ShowAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowAnswerField, value) != true)) {
                    this.ShowAnswerField = value;
                    this.RaisePropertyChanged("ShowAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTraining {
            get {
                return this.StartTrainingField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTrainingField, value) != true)) {
                    this.StartTrainingField = value;
                    this.RaisePropertyChanged("StartTraining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statistics {
            get {
                return this.StatisticsField;
            }
            set {
                if ((object.ReferenceEquals(this.StatisticsField, value) != true)) {
                    this.StatisticsField = value;
                    this.RaisePropertyChanged("Statistics");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TheCorrectAnswer {
            get {
                return this.TheCorrectAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.TheCorrectAnswerField, value) != true)) {
                    this.TheCorrectAnswerField = value;
                    this.RaisePropertyChanged("TheCorrectAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnflagContent {
            get {
                return this.UnflagContentField;
            }
            set {
                if ((object.ReferenceEquals(this.UnflagContentField, value) != true)) {
                    this.UnflagContentField = value;
                    this.RaisePropertyChanged("UnflagContent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyDisplayNames", Namespace="http://schemas.datacontract.org/2004/07/JJ.Presentation.QuestionAndAnswer.AppService")]
    [System.SerializableAttribute()]
    public partial class PropertyDisplayNames : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswersCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrectAnswerCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlagStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsCorrectAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsManualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastModifiedByUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnswersCount {
            get {
                return this.AnswersCountField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswersCountField, value) != true)) {
                    this.AnswersCountField = value;
                    this.RaisePropertyChanged("AnswersCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrectAnswerCount {
            get {
                return this.CorrectAnswerCountField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrectAnswerCountField, value) != true)) {
                    this.CorrectAnswerCountField = value;
                    this.RaisePropertyChanged("CorrectAnswerCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateTimeField, value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlagStatus {
            get {
                return this.FlagStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.FlagStatusField, value) != true)) {
                    this.FlagStatusField = value;
                    this.RaisePropertyChanged("FlagStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.IsActiveField, value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsCorrectAnswer {
            get {
                return this.IsCorrectAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.IsCorrectAnswerField, value) != true)) {
                    this.IsCorrectAnswerField = value;
                    this.RaisePropertyChanged("IsCorrectAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsManual {
            get {
                return this.IsManualField;
            }
            set {
                if ((object.ReferenceEquals(this.IsManualField, value) != true)) {
                    this.IsManualField = value;
                    this.RaisePropertyChanged("IsManual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedByUser {
            get {
                return this.LastModifiedByUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifiedByUserField, value) != true)) {
                    this.LastModifiedByUserField = value;
                    this.RaisePropertyChanged("LastModifiedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionCategory {
            get {
                return this.QuestionCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionCategoryField, value) != true)) {
                    this.QuestionCategoryField = value;
                    this.RaisePropertyChanged("QuestionCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionLink {
            get {
                return this.QuestionLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionLinkField, value) != true)) {
                    this.QuestionLinkField = value;
                    this.RaisePropertyChanged("QuestionLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionLinks {
            get {
                return this.QuestionLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionLinksField, value) != true)) {
                    this.QuestionLinksField = value;
                    this.RaisePropertyChanged("QuestionLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionType {
            get {
                return this.QuestionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTypeField, value) != true)) {
                    this.QuestionTypeField = value;
                    this.RaisePropertyChanged("QuestionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Questions {
            get {
                return this.QuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionsField, value) != true)) {
                    this.QuestionsField = value;
                    this.RaisePropertyChanged("Questions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Runs {
            get {
                return this.RunsField;
            }
            set {
                if ((object.ReferenceEquals(this.RunsField, value) != true)) {
                    this.RunsField = value;
                    this.RaisePropertyChanged("Runs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResources", Namespace="http://schemas.datacontract.org/2004/07/JJ.Presentation.QuestionAndAnswer.AppService")]
    [System.SerializableAttribute()]
    public partial class CommonResources : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CancelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Add {
            get {
                return this.AddField;
            }
            set {
                if ((object.ReferenceEquals(this.AddField, value) != true)) {
                    this.AddField = value;
                    this.RaisePropertyChanged("Add");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cancel {
            get {
                return this.CancelField;
            }
            set {
                if ((object.ReferenceEquals(this.CancelField, value) != true)) {
                    this.CancelField = value;
                    this.RaisePropertyChanged("Cancel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Delete {
            get {
                return this.DeleteField;
            }
            set {
                if ((object.ReferenceEquals(this.DeleteField, value) != true)) {
                    this.DeleteField = value;
                    this.RaisePropertyChanged("Delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Edit {
            get {
                return this.EditField;
            }
            set {
                if ((object.ReferenceEquals(this.EditField, value) != true)) {
                    this.EditField = value;
                    this.RaisePropertyChanged("Edit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogIn {
            get {
                return this.LogInField;
            }
            set {
                if ((object.ReferenceEquals(this.LogInField, value) != true)) {
                    this.LogInField = value;
                    this.RaisePropertyChanged("LogIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogOut {
            get {
                return this.LogOutField;
            }
            set {
                if ((object.ReferenceEquals(this.LogOutField, value) != true)) {
                    this.LogOutField = value;
                    this.RaisePropertyChanged("LogOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string New {
            get {
                return this.NewField;
            }
            set {
                if ((object.ReferenceEquals(this.NewField, value) != true)) {
                    this.NewField = value;
                    this.RaisePropertyChanged("New");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string None {
            get {
                return this.NoneField;
            }
            set {
                if ((object.ReferenceEquals(this.NoneField, value) != true)) {
                    this.NoneField = value;
                    this.RaisePropertyChanged("None");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remove {
            get {
                return this.RemoveField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoveField, value) != true)) {
                    this.RemoveField = value;
                    this.RaisePropertyChanged("Remove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Save {
            get {
                return this.SaveField;
            }
            set {
                if ((object.ReferenceEquals(this.SaveField, value) != true)) {
                    this.SaveField = value;
                    this.RaisePropertyChanged("Save");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Search {
            get {
                return this.SearchField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchField, value) != true)) {
                    this.SearchField = value;
                    this.RaisePropertyChanged("Search");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Yes {
            get {
                return this.YesField;
            }
            set {
                if ((object.ReferenceEquals(this.YesField, value) != true)) {
                    this.YesField = value;
                    this.RaisePropertyChanged("Yes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResourceService.IResourceService")]
    public interface IResourceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetMessages", ReplyAction="http://tempuri.org/IResourceService/GetMessagesResponse")]
        JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.Messages GetMessages(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetMessages", ReplyAction="http://tempuri.org/IResourceService/GetMessagesResponse")]
        System.Threading.Tasks.Task<JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.Messages> GetMessagesAsync(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetTitles", ReplyAction="http://tempuri.org/IResourceService/GetTitlesResponse")]
        JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.Titles GetTitles(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetTitles", ReplyAction="http://tempuri.org/IResourceService/GetTitlesResponse")]
        System.Threading.Tasks.Task<JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.Titles> GetTitlesAsync(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetPropertyDisplayNames", ReplyAction="http://tempuri.org/IResourceService/GetPropertyDisplayNamesResponse")]
        JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.PropertyDisplayNames GetPropertyDisplayNames(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetPropertyDisplayNames", ReplyAction="http://tempuri.org/IResourceService/GetPropertyDisplayNamesResponse")]
        System.Threading.Tasks.Task<JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.PropertyDisplayNames> GetPropertyDisplayNamesAsync(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetCommonResources", ReplyAction="http://tempuri.org/IResourceService/GetCommonResourcesResponse")]
        JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.CommonResources GetCommonResources(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetCommonResources", ReplyAction="http://tempuri.org/IResourceService/GetCommonResourcesResponse")]
        System.Threading.Tasks.Task<JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.CommonResources> GetCommonResourcesAsync(string cultureName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResourceServiceChannel : JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.IResourceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourceServiceClient : System.ServiceModel.ClientBase<JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.IResourceService>, JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.IResourceService {
        
        public ResourceServiceClient() {
        }
        
        public ResourceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.Messages GetMessages(string cultureName) {
            return base.Channel.GetMessages(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.Messages> GetMessagesAsync(string cultureName) {
            return base.Channel.GetMessagesAsync(cultureName);
        }
        
        public JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.Titles GetTitles(string cultureName) {
            return base.Channel.GetTitles(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.Titles> GetTitlesAsync(string cultureName) {
            return base.Channel.GetTitlesAsync(cultureName);
        }
        
        public JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.PropertyDisplayNames GetPropertyDisplayNames(string cultureName) {
            return base.Channel.GetPropertyDisplayNames(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.PropertyDisplayNames> GetPropertyDisplayNamesAsync(string cultureName) {
            return base.Channel.GetPropertyDisplayNamesAsync(cultureName);
        }
        
        public JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.CommonResources GetCommonResources(string cultureName) {
            return base.Channel.GetCommonResources(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Presentation.QuestionAndAnswer.AppService.DemoClient.ResourceService.CommonResources> GetCommonResourcesAsync(string cultureName) {
            return base.Channel.GetCommonResourcesAsync(cultureName);
        }
    }
}
