//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.18444
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Business.QuestionAndAnswer.Resources {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class PropertyDisplayNames {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal PropertyDisplayNames() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JJ.Business.QuestionAndAnswer.Resources.PropertyDisplayNames", typeof(PropertyDisplayNames).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Answer.
		/// </summary>
		public static string Answer {
			get {
				return ResourceManager.GetString("Answer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to AnswersCount.
		/// </summary>
		public static string AnswersCount {
			get {
				return ResourceManager.GetString("AnswersCount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Categories.
		/// </summary>
		public static string Categories {
			get {
				return ResourceManager.GetString("Categories", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Category.
		/// </summary>
		public static string Category {
			get {
				return ResourceManager.GetString("Category", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Comment.
		/// </summary>
		public static string Comment {
			get {
				return ResourceManager.GetString("Comment", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to CorrectAnswerCount.
		/// </summary>
		public static string CorrectAnswerCount {
			get {
				return ResourceManager.GetString("CorrectAnswerCount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to DateTime.
		/// </summary>
		public static string DateTime {
			get {
				return ResourceManager.GetString("DateTime", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		public static string Description {
			get {
				return ResourceManager.GetString("Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to FlagStatus.
		/// </summary>
		public static string FlagStatus {
			get {
				return ResourceManager.GetString("FlagStatus", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ID.
		/// </summary>
		public static string ID {
			get {
				return ResourceManager.GetString("ID", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to IsActive.
		/// </summary>
		public static string IsActive {
			get {
				return ResourceManager.GetString("IsActive", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to IsCorrectAnswer.
		/// </summary>
		public static string IsCorrectAnswer {
			get {
				return ResourceManager.GetString("IsCorrectAnswer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to IsManual.
		/// </summary>
		public static string IsManual {
			get {
				return ResourceManager.GetString("IsManual", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to LastModifiedByUser.
		/// </summary>
		public static string LastModifiedByUser {
			get {
				return ResourceManager.GetString("LastModifiedByUser", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Password.
		/// </summary>
		public static string Password {
			get {
				return ResourceManager.GetString("Password", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Question.
		/// </summary>
		public static string Question {
			get {
				return ResourceManager.GetString("Question", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to QuestionCategory.
		/// </summary>
		public static string QuestionCategory {
			get {
				return ResourceManager.GetString("QuestionCategory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to QuestionLink.
		/// </summary>
		public static string QuestionLink {
			get {
				return ResourceManager.GetString("QuestionLink", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to QuestionLinks.
		/// </summary>
		public static string QuestionLinks {
			get {
				return ResourceManager.GetString("QuestionLinks", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Questions.
		/// </summary>
		public static string Questions {
			get {
				return ResourceManager.GetString("Questions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to QuestionType.
		/// </summary>
		public static string QuestionType {
			get {
				return ResourceManager.GetString("QuestionType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Runs.
		/// </summary>
		public static string Runs {
			get {
				return ResourceManager.GetString("Runs", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Source.
		/// </summary>
		public static string Source {
			get {
				return ResourceManager.GetString("Source", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Text.
		/// </summary>
		public static string Text {
			get {
				return ResourceManager.GetString("Text", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Url.
		/// </summary>
		public static string Url {
			get {
				return ResourceManager.GetString("Url", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to UserName.
		/// </summary>
		public static string UserName {
			get {
				return ResourceManager.GetString("UserName", resourceCulture);
			}
		}
	}
}
