//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Business.QuestionAndAnswer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JJ.Business.QuestionAndAnswer.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        internal static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Answers.
        /// </summary>
        internal static string AnswersCount {
            get {
                return ResourceManager.GetString("AnswersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the following question?.
        /// </summary>
        internal static string AreYouSureYouWishToDeleteTheFollowingQuestion {
            get {
                return ResourceManager.GetString("AreYouSureYouWishToDeleteTheFollowingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Categories.
        /// </summary>
        internal static string AvailableCategories {
            get {
                return ResourceManager.GetString("AvailableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories_Accusative {
            get {
                return ResourceManager.GetString("Categories_Accusative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagged By.
        /// </summary>
        internal static string ContentFlaggedBy {
            get {
                return ResourceManager.GetString("ContentFlaggedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Flaggings.
        /// </summary>
        internal static string ContentFlags {
            get {
                return ResourceManager.GetString("ContentFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagged.
        /// </summary>
        internal static string ContentIsFlagged {
            get {
                return ResourceManager.GetString("ContentIsFlagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Management.
        /// </summary>
        internal static string ContentManagement {
            get {
                return ResourceManager.GetString("ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Sources &amp; Imports.
        /// </summary>
        internal static string ContentSourcesAndImports {
            get {
                return ResourceManager.GetString("ContentSourcesAndImports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of correct answers.
        /// </summary>
        internal static string CorrectAnswerCount {
            get {
                return ResourceManager.GetString("CorrectAnswerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Question.
        /// </summary>
        internal static string CreateQuestion {
            get {
                return ResourceManager.GetString("CreateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Manually edited questions will not be overwritten by automatic processes.).
        /// </summary>
        internal static string ExplanationOfIsManualWithParenthesis {
            get {
                return ResourceManager.GetString("ExplanationOfIsManualWithParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        internal static string FlagContent {
            get {
                return ResourceManager.GetString("FlagContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagged Content.
        /// </summary>
        internal static string FlaggedContent {
            get {
                return ResourceManager.GetString("FlaggedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Status.
        /// </summary>
        internal static string FlagStatus {
            get {
                return ResourceManager.GetString("FlagStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Active Flaggings.
        /// </summary>
        internal static string HasActiveFlags {
            get {
                return ResourceManager.GetString("HasActiveFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Answer.
        /// </summary>
        internal static string HideAnswer {
            get {
                return ResourceManager.GetString("HideAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is correct answer.
        /// </summary>
        internal static string IsCorrectAnswer {
            get {
                return ResourceManager.GetString("IsCorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually edited.
        /// </summary>
        internal static string IsManual {
            get {
                return ResourceManager.GetString("IsManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified by.
        /// </summary>
        internal static string LastModifiedByUser {
            get {
                return ResourceManager.GetString("LastModifiedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories available..
        /// </summary>
        internal static string NoCategoriesAvailable {
            get {
                return ResourceManager.GetString("NoCategoriesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No questions found..
        /// </summary>
        internal static string NoQuestionsFound {
            get {
                return ResourceManager.GetString("NoQuestionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question_Accusative {
            get {
                return ResourceManager.GetString("Question_Accusative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Category.
        /// </summary>
        internal static string QuestionCategory {
            get {
                return ResourceManager.GetString("QuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string QuestionLink {
            get {
                return ResourceManager.GetString("QuestionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string QuestionLinks {
            get {
                return ResourceManager.GetString("QuestionLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Type.
        /// </summary>
        internal static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs.
        /// </summary>
        internal static string Runs {
            get {
                return ResourceManager.GetString("Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Answer.
        /// </summary>
        internal static string ShowAnswer {
            get {
                return ResourceManager.GetString("ShowAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Training.
        /// </summary>
        internal static string StartTraining {
            get {
                return ResourceManager.GetString("StartTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correct anwer is.
        /// </summary>
        internal static string TheCorrectAnswer {
            get {
                return ResourceManager.GetString("TheCorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unflag.
        /// </summary>
        internal static string UnflagContent {
            get {
                return ResourceManager.GetString("UnflagContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have JavaScript disabled. Here is the alternative content:.
        /// </summary>
        internal static string YouHaveJavaScriptDisabled {
            get {
                return ResourceManager.GetString("YouHaveJavaScriptDisabled", resourceCulture);
            }
        }
    }
}
