//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.34209
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Presentation.QuestionAndAnswer.Resources {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Messages {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Messages() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JJ.Presentation.QuestionAndAnswer.Resources.Messages", typeof(Messages).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to AreYouSureYouWishToDeleteTheFollowingQuestion.
		/// </summary>
		public static string AreYouSureYouWishToDeleteTheFollowingQuestion {
			get {
				return ResourceManager.GetString("AreYouSureYouWishToDeleteTheFollowingQuestion", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ExplanationOfIsManualWithParenthesis.
		/// </summary>
		public static string ExplanationOfIsManualWithParenthesis {
			get {
				return ResourceManager.GetString("ExplanationOfIsManualWithParenthesis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to NoCategoriesAvailable.
		/// </summary>
		public static string NoCategoriesAvailable {
			get {
				return ResourceManager.GetString("NoCategoriesAvailable", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to NoQuestionsFound.
		/// </summary>
		public static string NoQuestionsFound {
			get {
				return ResourceManager.GetString("NoQuestionsFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to You are not authorized to view this content..
		/// </summary>
		public static string NotAuthorized {
			get {
				return ResourceManager.GetString("NotAuthorized", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to QuestionIsDeleted.
		/// </summary>
		public static string QuestionIsDeleted {
			get {
				return ResourceManager.GetString("QuestionIsDeleted", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to YouHaveNoJavaScript.
		/// </summary>
		public static string YouHaveNoJavaScript {
			get {
				return ResourceManager.GetString("YouHaveNoJavaScript", resourceCulture);
			}
		}
	}
}
