//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Presentation.QuestionAndAnswer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JJ.Presentation.QuestionAndAnswer.Resources.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdditionalInformation.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailableCategories.
        /// </summary>
        public static string AvailableCategories {
            get {
                return ResourceManager.GetString("AvailableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackToList.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentFlaggedBy.
        /// </summary>
        public static string ContentFlaggedBy {
            get {
                return ResourceManager.GetString("ContentFlaggedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentFlags.
        /// </summary>
        public static string ContentFlags {
            get {
                return ResourceManager.GetString("ContentFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentIsFlagged.
        /// </summary>
        public static string ContentIsFlagged {
            get {
                return ResourceManager.GetString("ContentIsFlagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentManagement.
        /// </summary>
        public static string ContentManagement {
            get {
                return ResourceManager.GetString("ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentSourcesAndImports.
        /// </summary>
        public static string ContentSourcesAndImports {
            get {
                return ResourceManager.GetString("ContentSourcesAndImports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateQuestion.
        /// </summary>
        public static string CreateQuestion {
            get {
                return ResourceManager.GetString("CreateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteQuestion.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditQuestion.
        /// </summary>
        public static string EditQuestion {
            get {
                return ResourceManager.GetString("EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlagContent.
        /// </summary>
        public static string FlagContent {
            get {
                return ResourceManager.GetString("FlagContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlaggedContent.
        /// </summary>
        public static string FlaggedContent {
            get {
                return ResourceManager.GetString("FlaggedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HasActiveFlags.
        /// </summary>
        public static string HasActiveFlags {
            get {
                return ResourceManager.GetString("HasActiveFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideAnswer.
        /// </summary>
        public static string HideAnswer {
            get {
                return ResourceManager.GetString("HideAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextQuestion.
        /// </summary>
        public static string NextQuestion {
            get {
                return ResourceManager.GetString("NextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoQuestionsFound.
        /// </summary>
        public static string NoQuestionsFound {
            get {
                return ResourceManager.GetString("NoQuestionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionDetails.
        /// </summary>
        public static string QuestionDetails {
            get {
                return ResourceManager.GetString("QuestionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectCategories.
        /// </summary>
        public static string SelectCategories {
            get {
                return ResourceManager.GetString("SelectCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowAnswer.
        /// </summary>
        public static string ShowAnswer {
            get {
                return ResourceManager.GetString("ShowAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTraining.
        /// </summary>
        public static string StartTraining {
            get {
                return ResourceManager.GetString("StartTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheCorrectAnswer.
        /// </summary>
        public static string TheCorrectAnswer {
            get {
                return ResourceManager.GetString("TheCorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnflagContent.
        /// </summary>
        public static string UnflagContent {
            get {
                return ResourceManager.GetString("UnflagContent", resourceCulture);
            }
        }
    }
}
