//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionDetailViewModel", Namespace="http://schemas.datacontract.org/2004/07/JJ.Apps.QuestionAndAnswer.ViewModels")]
    [System.SerializableAttribute()]
    public partial class QuestionDetailViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnswerIsVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NotFoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAnswerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AnswerIsVisible {
            get {
                return this.AnswerIsVisibleField;
            }
            set {
                if ((this.AnswerIsVisibleField.Equals(value) != true)) {
                    this.AnswerIsVisibleField = value;
                    this.RaisePropertyChanged("AnswerIsVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NotFound {
            get {
                return this.NotFoundField;
            }
            set {
                if ((this.NotFoundField.Equals(value) != true)) {
                    this.NotFoundField = value;
                    this.RaisePropertyChanged("NotFound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAnswer {
            get {
                return this.UserAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAnswerField, value) != true)) {
                    this.UserAnswerField = value;
                    this.RaisePropertyChanged("UserAnswer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuestionService.IQuestionService")]
    public interface IQuestionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/NextQuestion", ReplyAction="http://tempuri.org/IQuestionService/NextQuestionResponse")]
        JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel NextQuestion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/NextQuestion", ReplyAction="http://tempuri.org/IQuestionService/NextQuestionResponse")]
        System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel> NextQuestionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/ShowQuestion", ReplyAction="http://tempuri.org/IQuestionService/ShowQuestionResponse")]
        JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel ShowQuestion(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/ShowQuestion", ReplyAction="http://tempuri.org/IQuestionService/ShowQuestionResponse")]
        System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel> ShowQuestionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/ShowAnswer", ReplyAction="http://tempuri.org/IQuestionService/ShowAnswerResponse")]
        JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel ShowAnswer(JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel viewModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/ShowAnswer", ReplyAction="http://tempuri.org/IQuestionService/ShowAnswerResponse")]
        System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel> ShowAnswerAsync(JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel viewModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/HideAnswer", ReplyAction="http://tempuri.org/IQuestionService/HideAnswerResponse")]
        JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel HideAnswer(JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel viewModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/HideAnswer", ReplyAction="http://tempuri.org/IQuestionService/HideAnswerResponse")]
        System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel> HideAnswerAsync(JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel viewModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuestionServiceChannel : JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.IQuestionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuestionServiceClient : System.ServiceModel.ClientBase<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.IQuestionService>, JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.IQuestionService {
        
        public QuestionServiceClient() {
        }
        
        public QuestionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuestionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel NextQuestion() {
            return base.Channel.NextQuestion();
        }
        
        public System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel> NextQuestionAsync() {
            return base.Channel.NextQuestionAsync();
        }
        
        public JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel ShowQuestion(int id) {
            return base.Channel.ShowQuestion(id);
        }
        
        public System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel> ShowQuestionAsync(int id) {
            return base.Channel.ShowQuestionAsync(id);
        }
        
        public JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel ShowAnswer(JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel viewModel) {
            return base.Channel.ShowAnswer(viewModel);
        }
        
        public System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel> ShowAnswerAsync(JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel viewModel) {
            return base.Channel.ShowAnswerAsync(viewModel);
        }
        
        public JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel HideAnswer(JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel viewModel) {
            return base.Channel.HideAnswer(viewModel);
        }
        
        public System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel> HideAnswerAsync(JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.QuestionService.QuestionDetailViewModel viewModel) {
            return base.Channel.HideAnswerAsync(viewModel);
        }
    }
}
