//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resource", Namespace="http://schemas.datacontract.org/2004/07/JJ.Apps.QuestionAndAnswer.WcfService")]
    [System.SerializableAttribute()]
    public partial class Resource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResourceService.IResourceService")]
    public interface IResourceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetAllTitles", ReplyAction="http://tempuri.org/IResourceService/GetAllTitlesResponse")]
        JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetAllTitles(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetAllTitles", ReplyAction="http://tempuri.org/IResourceService/GetAllTitlesResponse")]
        System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetAllTitlesAsync(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetTitles", ReplyAction="http://tempuri.org/IResourceService/GetTitlesResponse")]
        JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetTitles(string cultureName, string[] resourceNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetTitles", ReplyAction="http://tempuri.org/IResourceService/GetTitlesResponse")]
        System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetTitlesAsync(string cultureName, string[] resourceNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetAllLabels", ReplyAction="http://tempuri.org/IResourceService/GetAllLabelsResponse")]
        JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetAllLabels(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetAllLabels", ReplyAction="http://tempuri.org/IResourceService/GetAllLabelsResponse")]
        System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetAllLabelsAsync(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetLabels", ReplyAction="http://tempuri.org/IResourceService/GetLabelsResponse")]
        JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetLabels(string cultureName, string[] resourceNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetLabels", ReplyAction="http://tempuri.org/IResourceService/GetLabelsResponse")]
        System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetLabelsAsync(string cultureName, string[] resourceNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetAllMessages", ReplyAction="http://tempuri.org/IResourceService/GetAllMessagesResponse")]
        JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetAllMessages(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetAllMessages", ReplyAction="http://tempuri.org/IResourceService/GetAllMessagesResponse")]
        System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetAllMessagesAsync(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetMessages", ReplyAction="http://tempuri.org/IResourceService/GetMessagesResponse")]
        JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetMessages(string cultureName, string[] resourceNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetMessages", ReplyAction="http://tempuri.org/IResourceService/GetMessagesResponse")]
        System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetMessagesAsync(string cultureName, string[] resourceNames);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResourceServiceChannel : JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.IResourceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourceServiceClient : System.ServiceModel.ClientBase<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.IResourceService>, JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.IResourceService {
        
        public ResourceServiceClient() {
        }
        
        public ResourceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetAllTitles(string cultureName) {
            return base.Channel.GetAllTitles(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetAllTitlesAsync(string cultureName) {
            return base.Channel.GetAllTitlesAsync(cultureName);
        }
        
        public JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetTitles(string cultureName, string[] resourceNames) {
            return base.Channel.GetTitles(cultureName, resourceNames);
        }
        
        public System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetTitlesAsync(string cultureName, string[] resourceNames) {
            return base.Channel.GetTitlesAsync(cultureName, resourceNames);
        }
        
        public JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetAllLabels(string cultureName) {
            return base.Channel.GetAllLabels(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetAllLabelsAsync(string cultureName) {
            return base.Channel.GetAllLabelsAsync(cultureName);
        }
        
        public JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetLabels(string cultureName, string[] resourceNames) {
            return base.Channel.GetLabels(cultureName, resourceNames);
        }
        
        public System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetLabelsAsync(string cultureName, string[] resourceNames) {
            return base.Channel.GetLabelsAsync(cultureName, resourceNames);
        }
        
        public JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetAllMessages(string cultureName) {
            return base.Channel.GetAllMessages(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetAllMessagesAsync(string cultureName) {
            return base.Channel.GetAllMessagesAsync(cultureName);
        }
        
        public JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[] GetMessages(string cultureName, string[] resourceNames) {
            return base.Channel.GetMessages(cultureName, resourceNames);
        }
        
        public System.Threading.Tasks.Task<JJ.Apps.QuestionAndAnswer.WcfService.DemoClient.ResourceService.Resource[]> GetMessagesAsync(string cultureName, string[] resourceNames) {
            return base.Channel.GetMessagesAsync(cultureName, resourceNames);
        }
    }
}
